src/Entity/Hauptbuch.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HauptbuchRepository")
 */
class Hauptbuch
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $soll;

    /**
     * @ORM\Column(type="integer")
     */
    private $haben;

    /**
     * @ORM\Column(type="date")
     */
    private $datum;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $beschreibung;

    /**
     * @ORM\Column(type="float")
     */
    private $betrag;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $beleg;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSoll(): ?int
    {
        return $this->soll;
    }

    public function setSoll(int $soll): self
    {
        $this->soll = $soll;

        return $this;
    }

    public function getHaben(): ?int
    {
        return $this->haben;
    }

    public function setHaben(int $haben): self
    {
        $this->haben = $haben;

        return $this;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getBeschreibung(): ?string
    {
        return $this->beschreibung;
    }

    public function setBeschreibung(?string $beschreibung): self
    {
        $this->beschreibung = $beschreibung;

        return $this;
    }

    public function getBetrag(): ?float
    {
        return $this->betrag;
    }

    public function setBetrag(float $betrag): self
    {
        $this->betrag = $betrag;

        return $this;
    }

    public function getBeleg(): ?string
    {
        return $this->beleg;
    }

    public function setBeleg(?string $beleg): self
    {
        $this->beleg = $beleg;

        return $this;
    }

    // Nicht in DB
    public function getSollT(): ?string
    {
        return $this->soll;
    }

    public function setSollT(string $soll): self
    {
        $this->soll = $soll;

        return $this;
    }

    public function getHabenT(): ?string
    {
        return $this->haben;
    }

    public function setHabenT(string $haben): self
    {
        $this->haben = $haben;

        return $this;
    }
}

src/Controller/KontoauszugController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Plugins;

use App\Entity\Kontenplan;
use App\Entity\Hauptbuch;

use App\Service\Kontostand;

// Include Dompdf required namespaces
use Dompdf\Dompdf;
use Dompdf\Options;

// Include PhpSpreadsheet required namespaces
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class KontoauszugController extends AbstractController
{
    /**
     * @Route("/kontoauszug", name="kontoauszug")
     */
    public function index(Plugins $plugins) {
        $this->denyAccessUnlessGranted('ROLE_USER');
        // -- Liste verfügbarer Konti
        // aus DB auslesen
        $konti = $this->getDoctrine()
                        ->getRepository(Kontenplan::class)->createQueryBuilder('p')
                        ->where('p.id4 IS NOT null')
                        ->andWhere('p.status != 0')
                        ->orderBy('p.id1', 'ASC')->addOrderBy('p.id2', 'ASC')->addOrderBy('p.id3', 'ASC')->addOrderBy('p.id4', 'ASC')
                        ->getQuery()->getResult();

        // Seite ausgeben
        return $this->render('kontoauszug/index.html.twig', [
            'plugins' => $plugins->get(),
            'konto' => false,
            'konti' => $konti,
            'buchungen' => false,
        ]);
    }

    /**
     * @Route("/kontoauszug/show/{id4}", name="kontoauszug_show")
     */
    public function show(Plugins $plugins, Kontostand $kontostand, $id4) {
        $this->denyAccessUnlessGranted('ROLE_USER');
        // -- Kontoauszug anzeigen
        // Konti aus DB auslesen
        $konti = $this->getDoctrine()
                        ->getRepository(Kontenplan::class)->createQueryBuilder('p')
                        ->where('p.id4 IS NOT null')
                        ->andWhere('p.status != 0')
                        ->orderBy('p.id1', 'ASC')->addOrderBy('p.id2', 'ASC')->addOrderBy('p.id3', 'ASC')->addOrderBy('p.id4', 'ASC')
                        ->getQuery()->getResult();

        // spezifisches Konto aus DB auslesen
        $konto = $this->getDoctrine()->getRepository(Kontenplan::class)->findBy(array('id4' => $id4))[0];

        // Buchungen für Könto aus DB auslesen
        $buchungen = $this->getDoctrine()
                        ->getRepository(Hauptbuch::class)->createQueryBuilder('p')
                        ->where('p.soll = '.$id4)->orWhere('p.haben = '.$id4)
                        ->orderBy('p.datum', 'ASC')
                        ->getQuery()->getResult();

        // Kontostand berechnen
        $saldo = $kontostand->get($id4,$this->getDoctrine());

        // Seite ausgeben
        return $this->render('kontoauszug/index.html.twig', [
            'plugins' => $plugins->get(),
            'konto' => $konto,
            'konti' => $konti,
            'buchungen' => $buchungen,
            'saldo' => $saldo,
        ]);
    }

    /**
     * @Route("/kontoauszug/export/pdf/{id4}/{orderby}/{order}", name="kontoauszug_export_pdf")
     */
    public function export_pdf(Kontostand $kontostand, $id4, $orderby, $order) {
        $this->denyAccessUnlessGranted('ROLE_USER');
        // -- Kontoauszug als PDF exportieren
        // Kontoinformationen aus DB
        $konto = $this->getDoctrine()->getRepository(Kontenplan::class)->findBy(array('id4' => $id4))[0];

        // Buchungssätze aus DB
        $buchungen = $this->getDoctrine()
                        ->getRepository(Hauptbuch::class)->createQueryBuilder('p')
                        ->where('p.soll = '.$id4)->orWhere('p.haben = '.$id4)
                        ->orderBy('p.'.$orderby, $order)
                        ->getQuery()->getResult();

        // Kontonamen aus DB laden (werden in Hauptbuch nur Kontonummern gespeichert)
        foreach($buchungen as $satz) {
            $sql = $this->getDoctrine()->getRepository(Kontenplan::class)->findBy(array("id4" => $satz->getSoll()))[0];
            $satz->setSollT($satz->getSoll().' - '.$sql->getName());

            $sql = $this->getDoctrine()->getRepository(Kontenplan::class)->findBy(array("id4" => $satz->getHaben()))[0];
            $satz->setHabenT($satz->getHaben().' - '.$sql->getName());
        }

        // Saldo berechnen
        $saldo = $kontostand->get($id4,$this->getDoctrine());

        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');
        $pdfOptions->set('isRemoteEnabled', TRUE);
        
        $dompdf = new Dompdf($pdfOptions);

        // PDF Design
        $html = $this->renderView('kontoauszug/pdf.html.twig', [
            'konto' => $konto,
            'buchungen' => $buchungen,
            'saldo' => $saldo,
        ]);
        
        $dompdf->loadHtml($html);
        
        $dompdf->setPaper('A4', 'landscape');

        $dompdf->render();

        // PDF ausgeben
        $dompdf->stream(date("Y-m-d").'-Kontoauszug-'.$konto->getId4().'.pdf', [
            "Attachment" => false
        ]);
    }

    /**
     * @Route("/kontoauszug/export/xlsx/{id4}", name="kontoauszug_export_xlsx")
     */
    public function export_xlsx($id4) {
        $this->denyAccessUnlessGranted('ROLE_USER');
        // -- Kontoauszug als XLSX (Excel) exportieren
        // Kontoinformationen aus DB
        $konto = $this->getDoctrine()->getRepository(Kontenplan::class)->findBy(array('id4' => $id4))[0];

        // Buchungssätze aus DB
        $buchungen = $this->getDoctrine()
                        ->getRepository(Hauptbuch::class)->createQueryBuilder('p')
                        ->where('p.soll = '.$id4)->orWhere('p.haben = '.$id4)
                        ->orderBy('p.datum', 'ASC')
                        ->getQuery()->getResult();

        // Kontonamen aus DB laden (werden in Hauptbuch nur Kontonummern gespeichert)
        foreach($buchungen as $satz) {
            $sql = $this->getDoctrine()->getRepository(Kontenplan::class)->findBy(array("id4" => $satz->getSoll()))[0];
            $satz->setSollT($satz->getSoll().' - '.$sql->getName());

            $sql = $this->getDoctrine()->getRepository(Kontenplan::class)->findBy(array("id4" => $satz->getHaben()))[0];
            $satz->setHabenT($satz->getHaben().' - '.$sql->getName());
        }

        // Definiere Headline in Excel-File
        $header = array("ID", "Datum", "Beschreibung", "Soll", "Soll-Kontoname", "Haben", "Haben-Kontoname", "Betrag", "Beleg");
        $data = array($header);

        foreach($buchungen as $satz) {
            // definiere Spalten
            $array = array(
                $satz->getId(),
                $satz->getDatum(),
                $satz->getBeschreibung(),
                explode(" - ",$satz->getSollT())[0],
                explode(" - ",$satz->getSollT())[1],
                explode(" - ",$satz->getHabenT())[0],
                explode(" - ",$satz->getHabenT())[1],
                $satz->getBetrag()/100,
                $satz->getBeleg()
            );
            $data[] = $array;
        }

        $spreadsheet = new Spreadsheet();
        
        /* @var $sheet \PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet */
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->fromArray($data, null, 'A1');
        $sheet->setTitle("Kontoauszug ".$konto->getId4());
        
        // Create your Office 2007 Excel (XLSX Format)
        $writer = new Xlsx($spreadsheet);
        
        // Create a Temporary file in the system
        $fileName = date("Y-m-d").'-Kontoauszug-'.$konto->getId4().'.xlsx';
        $temp_file = tempnam(sys_get_temp_dir(), $fileName);
        
        // Create the excel file in the tmp directory of the system
        $writer->save($temp_file);
        
        // Return the excel file as an attachment
        return $this->file($temp_file, $fileName, ResponseHeaderBag::DISPOSITION_INLINE);
    }
}

templates/kontoauszug/index.html.twig
{% extends 'base.html.twig' %}

{% block pagetitle %}Kontoauszug{% endblock %}

{% block body %}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Kontoauszug (abgerufen am {{ "now"|date("d.m.Y") }})</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-xl-12 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Konto</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">
                                    {% if konto %}
                                        {{konto.id4}} - {{konto.name}}
                                        <a href="{{ path('kontoauszug') }}" class="btn btn-primary btn-circle btn-sm ml-2" data-toggle="tooltip" data-placement="top" title="Bearbeiten"><i class="fas fa-edit"></i></a>
                                    {% else %}
                                        <select id="konto">
                                            <option selected disabled value="0">Bitte wählen...</option>
                                            <option disabled>----------</option>
                                            {% for konto in konti %}
                                                <option value="{{ konto.id4 }}">{{ konto.id4 }} - {{ konto.name }}</option>
                                            {% endfor %}
                                        </select>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-list fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if konto %}
            <p>
                <a href="" target="_blank" class="btn btn-success btn-icon-split mb-3 float-right" data-toggle="modal" data-target="#PDFmodal">
                    <span class="icon text-white-50">
                        <i class="fas fa-file-pdf"></i>
                    </span>
                    <span class="text">PDF</span>
                </a>
                <a href="/kontoauszug/export/xlsx/{{ konto.id4 }}" target="_blank" class="btn btn-success btn-icon-split mb-3 mr-2 float-right">
                    <span class="icon text-white-50">
                        <i class="fas fa-file-excel"></i>
                    </span>
                    <span class="text">Excel</span>
                </a>
            </p>
            <div class="mt-5">
                <table class="table table-striped" id="kontoauszug">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Datum</th>
                            <th scope="col">Beschreibung</th>
                            <th scope="col">SOLL</th>
                            <th scope="col">HABEN</th>
                            <th scope="col">Betrag</th>
                            <th scope="col">Beleg</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for buchung in buchungen %}
                            <tr>
                                <td>{{ buchung.id }}</td>
                                <td data-order="{{ buchung.datum|date('Ymd') }}">{{ buchung.datum|date('d.m.Y') }}</td>
                                <td>{{ buchung.beschreibung }}</td>
                                <td>{{ buchung.soll }}</td>
                                <td>{{ buchung.haben }}</td>
                                <td data-order="{{ buchung.betrag }}">CHF {{ ((buchung.betrag)/100)|number_format(2)|replace({ ',': '.'}) }}</td>
                                <td>{{ buchung.beleg }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th></th>
                            <th>{{ 'now'|date('d.m.Y') }}</th>
                            <th>Saldo</th>
                            <th></th>
                            <th></th>
                            <th>CHF {{ saldo|number_format(2)|replace({ ',': '.'}) }}</th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        {% endif %}
    </div>
</div>
{% if konto %}
<div class="modal fade" id="PDFmodal" tabindex="-1" role="dialog" aria-labelledby="PDFmodalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="PDFmodalLabel">PDF exportieren</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">Sortieren nach:
        <select id="orderby" class="ml-2">
            <option value="id">ID</option>
            <option value="datum" selected>Datum</option>
            <option value="beschreibung">Beschreibung</option>
            <option value="soll">Soll</option>
            <option value="haben">Haben</option>
            <option value="betrag">Betrag</option>
            <option value="beleg">Beleg</option>
        </select>
        <select id="order" class="ml-2">
            <option value="ASC" selected>A - Z</option>
            <option value="DESC">Z - A</option>
        </select>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Abbrechen</button>
        <button type="button" class="btn btn-primary" onClick="generatePDF()">Exportieren</button>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

{% block javascripts %}
<script src="{{ asset('js/datatables.js') }}"></script>
<link rel="stylesheet" href="{{ asset('css/datatables.css') }}">

<script>
$("#konto").on('change', function() {
    window.location.href = '{{ path('kontoauszug') }}/show/'+$(this).val();
});

$(document).ready( function () {
    $('#kontoauszug').DataTable( {
        "language": {
            "url": "{{ asset('js/datatables_german.json') }}"
        },
        "order": [[1, "desc"]]
    } );
} );

{% if konto %}
function generatePDF() {
    var url = '/kontoauszug/export/pdf/'+{{ konto.id4 }}+'/'+$('select#orderby').val()+'/'+$('select#order').val();
    window.open(url);
}
{% endif %}
</script>
{% endblock %}

templates/kontoauszug/pdf.html.twig
{% extends 'pdf.html.twig' %}

{% block pagetitle %}Kontoauszug - {{ konto.id4 }} {{ konto.name }}{% endblock %}

{% block body %}
<table width="100%" class="table table-striped mt-5 pt-2">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Datum</th>
            <th scope="col">Beschreibung</th>
            <th scope="col">SOLL</th>
            <th scope="col">HABEN</th>
            <th scope="col">Betrag</th>
            <th scope="col">Beleg(e)</th>
        </tr>
    </thead>
    <tbody>
        {% for buchung in buchungen %}
            <tr>
                <td>{{ buchung.id }}</td>
                <td>{{ buchung.datum|date('d.m.Y') }}</td>
                <td>{{ buchung.beschreibung }}</td>
                <td>{{ buchung.sollT }}</td>
                <td>{{ buchung.habenT }}</td>
                <td>CHF {{ ((buchung.betrag)/100)|number_format(2)|replace({ ',': '.'}) }}</td>
                <td>{{ buchung.beleg }}</td>
            </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th></th>
            <th>{{ 'now'|date('d.m.Y') }}</th>
            <th>Saldo</th>
            <th></th>
            <th></th>
            <th>CHF {{ saldo|number_format(2)|replace({ ',': '.'}) }}</th>
            <th></th>
        </tr>
    </tfoot>
</table>
{% endblock %}